---
- hosts: localhost
  gather_facts: fasle
  tasks:
    - command: "ls /homee"
      register: home_out
      ignore_errors: yes
    - debug: var=home_out
    - command: "ls /tmp"
      register: tmp_out
    - debug: var=tmp_out
---
 - hosts: localhost
   gather_facts: false
   tasks:
    - command: "ls /homee"
      register: out
      failed_when: out.rc==0
    - debug: var=out.stderr
    - command: "ls /homee"
      register: out
    - fail:
        msg: "Failed because rc is 0"
      when: out.rc==0
