---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
    - name: Info about ec2 using ec2_instance_facts
      ec2_instance_facts:
        region: ap-southeast-1
        filters:
         "tag:names": nodes
      register: ec2_instance_facts
      tags:
        - always
    - debug: var=ec2_instance_facts
    - set_fact:
    #      #msg: "{{ ec2_instance_facts | json_query('instances[*].network_interfaces(public_ip)') }} "
    #      #msg: "{{ ec2_instance_facts | json_query('[*].{Name: public_ip}') }} "
          msg: "{{ ec2_instance_facts | json_query('instances[*].public_ip_address') }}"
    - shell: echo -e "[server]\nlocalhost\n[ec2]" >/ansible/text
    - shell:
        cmd: echo "{{item}}" >>text
        chdir: /ansible
      with_items: "{{ msg }}"
