---
 - name: outputs
   hosts: localhost
   gather_facts: true
   tasks:
    - debug:
       msg: "{{ ansible_os_family }}"
      register: var1
    - debug:
        msg: THis is YUM
      when: var1.msg == 'RedHat'
