---
 - name: Http install
   hosts: ec2
   become: yes
   gather_facts: no
   tasks:
    - name: Install Python
      raw: rm /usr/bin/python
    - name: link
      raw: ln -s /usr/bin/python36 /usr/bin/python
      register: out
    - debug: var=out
