---
 - name: Http install
   hosts: ec2
   become: yes
   gather_facts: no
   tasks:
    - name: grep
      raw: yum list | grep python3
      register: data
    - name: debug
      debug: var=data

    - name: Install Python
      raw: yum -y install python36
